# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainwindowz0427.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1150, 738)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(220, 110, 671, 511))
        self.graphicsView.setObjectName("graphicsView")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 60, 206, 131))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.textEditCetou = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.textEditCetou.setSuffix("")
        self.textEditCetou.setDecimals(3)
        self.textEditCetou.setObjectName("textEditCetou")
        self.horizontalLayout.addWidget(self.textEditCetou)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.textEditCaiyang = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.textEditCaiyang.setSuffix("")
        self.textEditCaiyang.setDecimals(3)
        self.textEditCaiyang.setObjectName("textEditCaiyang")
        self.horizontalLayout_2.addWidget(self.textEditCaiyang)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.textEditXuanzhuan = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.textEditXuanzhuan.setSuffix("")
        self.textEditXuanzhuan.setDecimals(3)
        self.textEditXuanzhuan.setObjectName("textEditXuanzhuan")
        self.horizontalLayout_3.addWidget(self.textEditXuanzhuan)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 200, 181, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        self.textEditCeliangshuju = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEditCeliangshuju.setGeometry(QtCore.QRect(10, 20, 161, 121))
        self.textEditCeliangshuju.setObjectName("textEditCeliangshuju")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(900, 140, 211, 441))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.textEditWucha = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.textEditWucha.setEnabled(False)
        self.textEditWucha.setSuffix("")
        self.textEditWucha.setDecimals(3)
        self.textEditWucha.setObjectName("textEditWucha")
        self.horizontalLayout_4.addWidget(self.textEditWucha)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.textEditBiaozhuncha = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.textEditBiaozhuncha.setEnabled(False)
        self.textEditBiaozhuncha.setSuffix("")
        self.textEditBiaozhuncha.setDecimals(3)
        self.textEditBiaozhuncha.setObjectName("textEditBiaozhuncha")
        self.horizontalLayout_5.addWidget(self.textEditBiaozhuncha)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.textEditJuli = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.textEditJuli.setEnabled(False)
        self.textEditJuli.setSuffix("")
        self.textEditJuli.setDecimals(3)
        self.textEditJuli.setObjectName("textEditJuli")
        self.horizontalLayout_6.addWidget(self.textEditJuli)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.textEditYalijiao = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.textEditYalijiao.setEnabled(False)
        self.textEditYalijiao.setSuffix("")
        self.textEditYalijiao.setDecimals(3)
        self.textEditYalijiao.setObjectName("textEditYalijiao")
        self.horizontalLayout_7.addWidget(self.textEditYalijiao)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.textEditBzengyi = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.textEditBzengyi.setEnabled(False)
        self.textEditBzengyi.setObjectName("textEditBzengyi")
        self.horizontalLayout_8.addWidget(self.textEditBzengyi)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.textEditBzhihou = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.textEditBzhihou.setEnabled(False)
        self.textEditBzhihou.setObjectName("textEditBzhihou")
        self.horizontalLayout_9.addWidget(self.textEditBzhihou)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_10.addWidget(self.label_13)
        self.textEditGuzengyi = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.textEditGuzengyi.setEnabled(False)
        self.textEditGuzengyi.setObjectName("textEditGuzengyi")
        self.horizontalLayout_10.addWidget(self.textEditGuzengyi)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_11.addWidget(self.label_14)
        self.textEditGuzhihou = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.textEditGuzhihou.setEnabled(False)
        self.textEditGuzhihou.setObjectName("textEditGuzhihou")
        self.horizontalLayout_11.addWidget(self.textEditGuzhihou)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 380, 111, 281))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ButtonDaoru = QtWidgets.QPushButton(self.layoutWidget)
        self.ButtonDaoru.setObjectName("ButtonDaoru")
        self.verticalLayout_2.addWidget(self.ButtonDaoru)
        self.ButtonShiji = QtWidgets.QPushButton(self.layoutWidget)
        self.ButtonShiji.setObjectName("ButtonShiji")
        self.verticalLayout_2.addWidget(self.ButtonShiji)
        self.ButtonLilun = QtWidgets.QPushButton(self.layoutWidget)
        self.ButtonLilun.setObjectName("ButtonLilun")
        self.verticalLayout_2.addWidget(self.ButtonLilun)
        self.ButtonDuibi = QtWidgets.QPushButton(self.layoutWidget)
        self.ButtonDuibi.setObjectName("ButtonDuibi")
        self.verticalLayout_2.addWidget(self.ButtonDuibi)
        self.ButtonPiancha = QtWidgets.QPushButton(self.layoutWidget)
        self.ButtonPiancha.setObjectName("ButtonPiancha")
        self.verticalLayout_2.addWidget(self.ButtonPiancha)
        self.ButtonPinding = QtWidgets.QPushButton(self.layoutWidget)
        self.ButtonPinding.setObjectName("ButtonPinding")
        self.verticalLayout_2.addWidget(self.ButtonPinding)
        self.ButtonSave = QtWidgets.QPushButton(self.layoutWidget)
        self.ButtonSave.setObjectName("ButtonSave")
        self.verticalLayout_2.addWidget(self.ButtonSave)
        self.ButtonQingchu = QtWidgets.QPushButton(self.layoutWidget)
        self.ButtonQingchu.setObjectName("ButtonQingchu")
        self.verticalLayout_2.addWidget(self.ButtonQingchu)
        self.ButtonClose = QtWidgets.QPushButton(self.layoutWidget)
        self.ButtonClose.setObjectName("ButtonClose")
        self.verticalLayout_2.addWidget(self.ButtonClose)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "参数设置："))
        self.label_6.setText(_translate("MainWindow", "测头半径(mm)："))
        self.label_5.setText(_translate("MainWindow", "采样间隔(deg)："))
        self.label_4.setText(_translate("MainWindow", "样板旋转角度(deg)："))
        self.groupBox_2.setTitle(_translate("MainWindow", "测量数据："))
        self.groupBox_3.setTitle(_translate("MainWindow", "评定结果："))
        self.label_7.setText(_translate("MainWindow", "最大误差值(um)："))
        self.label_8.setText(_translate("MainWindow", "曲线拟合标准差(um)："))
        self.label_9.setText(_translate("MainWindow", "V点和B点距离(um)："))
        self.label_10.setText(_translate("MainWindow", "压力角误差(um/deg)："))
        self.label_11.setText(_translate("MainWindow", "B点增益误差(%)："))
        self.label_12.setText(_translate("MainWindow", "B点滞后误差(%)："))
        self.label_13.setText(_translate("MainWindow", "谷底增益误差(%)："))
        self.label_14.setText(_translate("MainWindow", "谷底滞后误差(%)："))
        self.ButtonDaoru.setText(_translate("MainWindow", "导入测量数据"))
        self.ButtonShiji.setText(_translate("MainWindow", "实际曲线"))
        self.ButtonLilun.setText(_translate("MainWindow", "理论曲线"))
        self.ButtonDuibi.setText(_translate("MainWindow", "曲线对比"))
        self.ButtonPiancha.setText(_translate("MainWindow", "评定偏差曲线"))
        self.ButtonPinding.setText(_translate("MainWindow", "评定结果"))
        self.ButtonSave.setText(_translate("MainWindow", "保存"))
        self.ButtonQingchu.setText(_translate("MainWindow", "清除"))
        self.ButtonClose.setText(_translate("MainWindow", "关闭"))

